### Creates a new patients entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Kaddddfka Final Test",
  "email": "kafdddka_final_test@example.com",
  "address": "Main Street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}


###