PUT http://localhost:8080/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe paglaaaa",
  "email": "john.doe@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1985-06-15"

}